name: Publish to Maven Repository

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build with Maven
        run: mvn package
        
      - name: Get version from release
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        
      - name: Checkout Maven repository
        uses: actions/checkout@v3
        with:
          repository: CroaBeast/repo
          path: maven-repo
          token: ${{ secrets.MAVEN_DEPLOY_TOKEN }}
          
      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
      - name: Deploy to Maven repository
        run: |
          # Create directory structure
          mkdir -p maven-repo/me/croabeast/${{ github.event.repository.name }}/${{ env.VERSION }}
          
          # Copy JAR file
          cp target/${{ github.event.repository.name }}-${{ env.VERSION }}.jar maven-repo/me/croabeast/${{ github.event.repository.name }}/${{ env.VERSION }}/
          
          # Create POM file
          cat > maven-repo/me/croabeast/${{ github.event.repository.name }}/${{ env.VERSION }}/${{ github.event.repository.name }}-${{ env.VERSION }}.pom << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>me.croabeast</groupId>
              <artifactId>${{ github.event.repository.name }}</artifactId>
              <version>${{ env.VERSION }}</version>
              <packaging>jar</packaging>
          </project>
          EOF
          
          # Update or create maven-metadata.xml
          cat > maven-repo/me/croabeast/${{ github.event.repository.name }}/maven-metadata.xml << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <metadata>
            <groupId>me.croabeast</groupId>
            <artifactId>${{ github.event.repository.name }}</artifactId>
            <versioning>
              <latest>${{ env.VERSION }}</latest>
              <release>${{ env.VERSION }}</release>
              <versions>
                <version>${{ env.VERSION }}</version>
              </versions>
              <lastUpdated>$(date +%Y%m%d%H%M%S)</lastUpdated>
            </versioning>
          </metadata>
          EOF
          
          # Commit and push changes
          cd maven-repo
          git add .
          git commit -m "Deploy ${{ github.event.repository.name }} ${{ env.VERSION }}"
          git push

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
